### PR TITLE
Refactor stanc3 dockerfiles for ocaml 4.14

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
See https://github.com/stan-dev/stanc3/pull/1366

### CODE REVIEW

**Comment by WardBrian** [comment]
The stanc branch is using 4.14.1, not 4.14.0. Not sure how much this will matter!

**Comment by serban-nicusor-toptal** [comment]
Hmmh good catch, I'll try a rebuild.

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian I've added the `--bare` flag here, is this ready to merge or we want to do it at the same time with https://github.com/stan-dev/stanc3/pull/1366 ? Enjoy the weekend!

**Comment by WardBrian** [comment]
Thanks @serban-nicusor-toptal !

**Pull request merged**
