### PR TITLE
Add file utility to stanc3 images

### PR DESCRIPTION
**Pull request by andrjohns**
Needed for [this PR](https://github.com/stan-dev/stanc3/pull/1311)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Hey, I'll rebuild and push this in a few hours when I get home.

**Comment by andrjohns** [comment]
> Hey, I'll rebuild and push this in a few hours when I get home.

Great! No rush

**Comment by serban-nicusor-toptal** [comment]
Hey, small update.
debian:buster-slim is not building anymore for all the archs we need, so I had to revert to an older image.
Right now I'm trying to figure out why it's failing in `multiarch` image when installing `core_kernel v0.14.2` ...

For the rest, they're at:
- `stanorg/stanc3:debianfi-v0.0.2`
- `stanorg/stanc3:staticfi-v0.0.2`

So we can test them separately and then just update the main pipeline with it. I'll push the other one as soon as I figure out that opam doesn't like.

**Comment by andrjohns** [comment]
Great, thanks!

**Comment by serban-nicusor-toptal** [comment]
Have you ever encountered this one ?
``` #11 [ 6/17] RUN eval $(opam env) opam install --debug core_kernel.v0.14.2
#11 0.338 [WARNING] Running as root is not recommended
#11 0.427 [WARNING] Running as root is not recommended
#11 0.440 00:00.022  GSTATE                          LOAD-GLOBAL-STATE @ /root/.opam
#11 0.442 00:00.032  RSTATE                          LOAD-REPOSITORY-STATE @ /root/.opam
#11 0.817 00:00.407  RSTATE                          Loaded /root/.opam/repo/state.cache in 0.372s
#11 121.5 02:01.122  SOLVER                          Solver is aspcud >= 1.9: using latest version criteria
#11 121.5 02:01.122  SOLVER                          Calling solver aspcud with criteria -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)
#11 141.7 02:21.260  SYSTEM                          [log-11-ffb3fd] (in 18.498s) aspcud /root/.opam/log/solver-in-11-5f1023 /root/.opam/log/solver-out-11-58c514 -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)
#11 141.7 02:21.260  SYSTEM                          rm /root/.opam/log/solver-in-11-5f1023
#11 141.7 02:21.261  SYSTEM                          rm /root/.opam/log/solver-out-11-58c514
#11 151.8 02:31.389  CUDF                            Solver call done in 30.267
#11 162.0 02:41.610  CLIENT                          conflict!
#11 162.0 Sorry, no solution found: there seems to be a problem with your request.
#11 162.0
#11 162.0 No solution found, exiting
#11 162.0 02:41.611  SYSTEM                          rm /root/.opam/default/.opam-switch/backup/state-20230414104521.export
#11 ERROR: process "/bin/sh -c eval $(opam env) opam install --debug core_kernel.v0.14.2" did not complete successfully: exit code: 20
```

There's no real useful output sadly but I know that package fails for sure.
I've tried with different buster-slim versions but can't get it to work, in the image itself nothing changed really but something related remote repositories did I think. Still trying to figure it out.

**Comment by andrjohns** [comment]
Hmm can't say I have. Did you want to leave this one with me? There's no rush to update the multiarch images, and I'm familiar with a few of the quirks from when I first put them together

**Comment by serban-nicusor-toptal** [comment]
Sure, I'll commit my changes.
Just FTR the latest image of Debian is not supporting all our multi-arch targets anymore.
What we used in the past: https://hub.docker.com/layers/library/debian/buster-20211115-slim/images/sha256-9ad9871d1ab8f29c2d32b7c1d807f8106ac173edf4c682c8cdc071db124694e7?context=explore
What we have now: https://hub.docker.com/layers/library/debian/buster-slim/images/sha256-603e7e0b2c5ee5dcfd1b1ba07b4598dd481b6afa6dcf348399428e72b0370a35?context=explore

They seem to have fixed the error message in 2.10+
I've tried to update opam as written here https://opam.ocaml.org/doc/Install.html
But their bash script is trying to get the binaries from github which they don't have for `linux/mips64le` so we can't install it like that ?
Apt is only at 2.0.3 which is old, they also point to an apt repository which seems to not be working.
The only option left is to build from sources ?

While trying to debug I also ran into:
```
#10 252.1 [ERROR] The compilation of ocaml-base-compiler failed at "/usr/bin/make -j23".
#10 252.1
#10 252.1 #=== ERROR while compiling ocaml-base-compiler.4.12.0 =========================#
#10 252.1 # context              2.0.3 | linux/mips64 |  | https://opam.ocaml.org#2fb2108f
#10 252.1 # path                 ~/.opam/4.12.0/.opam-switch/build/ocaml-base-compiler.4.12.0
#10 252.1 # command              /usr/bin/make -j23
#10 252.1 # exit-code            2
#10 252.1 # env-file             ~/.opam/log/ocaml-base-compiler-11-b1a82b.env
#10 252.1 # output-file          ~/.opam/log/ocaml-base-compiler-11-b1a82b.out
#10 252.1 ### output ###
#10 252.1 # Makefile:920: *** The native-code compiler is not supported on this platform.  Stop.
#10 252.1
#10 252.3 
#10 252.3
#10 252.3 <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
```

I was debugging with:
```
docker buildx build -t stanorg/stanc3:multiarchfi-v0.0.2 --platform linux/mips64le --build-arg PUID=990 --progress=plain --build-arg PGID=986 --push .
```

**Comment by WardBrian** [comment]
I think this didn't end up being needed? At any rate the relevant docker files now live in stanc3's repo

**Pull request closed without merging**
